#
# Configuration file
#

name: Jake Lane
description: Undergraduate Software Engineer
keywords: "jake lane, software, engineer, programmer, github"
disqus: jakelane
google_analytics: UA-36740143-1
url: http://jakelane.me/
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

# Navigation links
navigation:
- text: About Me
  url: /
- text: Blog
  url: /blog/
  layout: page
- text: Projects
  url: /projects/
  layout: project
- text: Contact
  url: /contact/

# Pagination
paginate: 3
paginate_path: "/blog/page:num"

sass:
  style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
